require 'plugins.packer'
require 'vimp'

require 'modules.opts'
require 'modules.setup'
require 'modules.eyecandy'
require 'modules.statusline'
-- require 'modules.lsp'

require 'plugins.rooter'
require 'plugins.dirvish'
require 'plugins.signify'
require 'plugins.vimtex'
require 'plugins.treesitter'
require 'plugins.coc'
require 'plugins.fzf'
-- require 'plugins.telescope'
-- require 'plugins.lspconfig'
-- require 'plugins.lsputils'
-- require 'plugins.completion'
