require 'plugins.packer'
require 'vimp'

require 'modules.opts'
require 'modules.setup'
require 'modules.eyecandy'
require 'modules.statusline'

require 'plugins.vimtex'
require 'plugins.dirvish'
require 'plugins.rooter'
require 'plugins.telescope'
require 'plugins.prettier'
require 'plugins.signify'

require 'plugins.qf'
require 'plugins.treesitter'
require 'plugins.lsp'
require 'plugins.completion'
require 'plugins.lsputils'
