vimp.nmap('<Space>gt', ':Files<CR>')
vimp.nmap('<Space>gT', ':GitFiles<CR>')
vimp.nmap('<Space>gb', ':Buffers<CR>')
vimp.nmap('<Space>gr', ':Rg<CR>')
vimp.nmap('<Space>gm', ':History<CR>')
vimp.nmap('<Space>gh', ':History:<CR>')
